/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.jFrame;

import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import main.Aeroporto;
import main.CustomComboBoxModel;
import main.DiasSemana;
import main.Manipulador;
import main.Voo;

/**
 *
 * @author Gean
 */
public class JFrameRoteiro extends javax.swing.JFrame {
    
    public JFrameSelecionarAero selecionar = null;
    
    /**
     * Creates new form JFrameRoteiro
     */
    public JFrameRoteiro() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelOrigem = new javax.swing.JLabel();
        jTextFieldOrigem = new javax.swing.JTextField();
        jLabelDestino = new javax.swing.JLabel();
        jTextFieldDestino = new javax.swing.JTextField();
        jButtonGerarRoteiro = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaRoteiro = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ROTEIRO DE VIAGEM");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelOrigem.setText("Origem: ");

        jTextFieldOrigem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldOrigemFocusLost(evt);
            }
        });

        jLabelDestino.setText("Destino: ");

        jTextFieldDestino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDestinoFocusLost(evt);
            }
        });

        jButtonGerarRoteiro.setText("Gerar Roteiro");
        jButtonGerarRoteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarRoteiroActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar em arquivo");

        jTextAreaRoteiro.setColumns(20);
        jTextAreaRoteiro.setRows(5);
        jScrollPane2.setViewportView(jTextAreaRoteiro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelOrigem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldOrigem))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelDestino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldDestino)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGerarRoteiro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSalvar)
                                .addGap(0, 475, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelOrigem))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonGerarRoteiro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDestino)
                    .addComponent(jTextFieldDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        JFramePrincipal.roteiro = null;
        
    }//GEN-LAST:event_formWindowClosing

    private void jTextFieldOrigemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldOrigemFocusLost
        
        String value = this.jTextFieldOrigem.getText().toUpperCase();
        
        if(!value.isEmpty()){
            List<Aeroporto> possibilidades = JFramePrincipal.plano.getAllAeroportosWith(value);
            
            switch(possibilidades.size()){
                case 0:
                    JOptionPane.showMessageDialog(null, "Aeroporto " + value + " inexistente", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    break;
                case 1:
                    this.jTextFieldOrigem.setText(possibilidades.get(0).toString());
                    break;
                default:
                    abrirSelecionarVoo(possibilidades, this.jTextFieldOrigem);
            }
        }
        
    }//GEN-LAST:event_jTextFieldOrigemFocusLost

    private void jTextFieldDestinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDestinoFocusLost
        String value = this.jTextFieldDestino.getText().toUpperCase();
        
        if(!value.isEmpty()){
            List<Aeroporto> possibilidades = JFramePrincipal.plano.getAllAeroportosWith(value);
            
            switch(possibilidades.size()){
                case 0:
                    JOptionPane.showMessageDialog(null, "Aeroporto " + value + " inexistente", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    break;
                case 1:
                    this.jTextFieldDestino.setText(possibilidades.get(0).toString());
                    break;
                default:
                    abrirSelecionarVoo(possibilidades, this.jTextFieldDestino);
            }
        }
    }//GEN-LAST:event_jTextFieldDestinoFocusLost

    private void jButtonGerarRoteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarRoteiroActionPerformed
        
        Aeroporto origem = JFramePrincipal.plano.getAeroporto(this.jTextFieldOrigem.getText());
        Aeroporto destino = JFramePrincipal.plano.getAeroporto(this.jTextFieldDestino.getText());
        
        List<Voo> menorCaminho = JFramePrincipal.plano.getMenorCaminho(origem, destino);
        
        int[] tempoDeVoo = Manipulador.getMinInTime(menorCaminho.get(menorCaminho.size()-1).getAeroportoChegada().getDistancia());
        
        this.jTextAreaRoteiro.setText("");
        this.jTextAreaRoteiro.append(String.format("Tempo de viagem = %02d:%02d\n", tempoDeVoo[0], tempoDeVoo[1]));
        menorCaminho.forEach(voo -> {
            this.jTextAreaRoteiro.append(String.format(
                    "(%s) %s -> %s\n",
                    voo.getCodVoo(),
                    voo.getAeroportoSaida(),
                    voo.getAeroportoChegada()
            ));
        });
        
    }//GEN-LAST:event_jButtonGerarRoteiroActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerarRoteiro;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelOrigem;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaRoteiro;
    private javax.swing.JTextField jTextFieldDestino;
    private javax.swing.JTextField jTextFieldOrigem;
    // End of variables declaration//GEN-END:variables

    private void abrirSelecionarVoo(List<Aeroporto> possibilidades, JTextField textField) {
        
        if(selecionar == null)
            selecionar = new JFrameSelecionarAero(possibilidades, textField);
        else{
            selecionar.setPossibilidades(possibilidades);
            selecionar.setOutput(textField);
        }
        selecionar.setVisible(true);
        
    }
}
